#!/bin/bash

directories=(
    "$HOME/.local/share/TelegramDesktop/tdata/user_data/cache/"
    "$HOME/.local/share/TelegramDesktop/tdata/user_data/media_cache/"
    "$HOME/.config/Code/Cache/"
    "$HOME/.config/Code/CachedExtensionVSIXs/"
    "$HOME/.config/Code/CachedData/"
    "$HOME/.config/discord/Cache/"
    "$HOME/.config/discord/Code Cache/"
    "$HOME/.cache/"
    "/var/cache/"
)

clean_directory() {
    local dir="$1"
    if [ -d "$dir" ]; then
        echo "Cleaning directory: $dir"
        sudo rm -rf "$dir"/* "$dir"/.[!.]* "$dir"/..?* 2>/dev/null
        echo "Cleaned: $dir"
    else
        echo "Directory does not exist: $dir"
    fi
}

for dir in "${directories[@]}"; do
    clean_directory "$dir"
done

echo "Cleanup completed!"
